[advisories]
version = 2
ignore = []
yanked = "deny"

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
    "NCSA",
]
confidence-threshold = 0.93
unused-allowed-license = "allow"

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
